return {
	"nvim-neo-tree/neo-tree.nvim",
	branch = "v3.x",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-tree/nvim-web-devicons",
		"MunifTanjim/nui.nvim",
	},
	cmd = "Neotree",
	keys = {
		{ "<C-b>", "<cmd>Neotree toggle left<CR>", desc = "Explorer" },
		{ "<leader>f", "<cmd>Neotree focus<CR>", desc = "Focus File Tree" },
		{ "<leader>c", "<cmd>Neotree close<CR>", desc = "Close Neo-tree" },
	},
	opts = {
		close_if_last_window = true,
		popup_border_style = "rounded",
		enable_git_status = true,
		enable_diagnostics = true,
		default_component_configs = {
			indent = {
				indent_size = 2,
				padding = 2,
				with_markers = true,
				indent_marker = "│",
				last_indent_marker = "└",
				highlight = "NeoTreeIndentMarker",
				with_expanders = nil,
				expander_collapsed = " ",
				expander_expanded = " ",
				expander_highlight = "NeoTreeExpander",
			},
			icon = { folder_closed = " ", folder_open = " ", folder_empty = " " },
			git_status = {
				symbols = {
					added = "+",
					modified = "~",
					deleted = "-",
					renamed = "→",
					untracked = "?",
					ignored = ".",
					unstaged = "!",
					staged = "*",
					conflict = "x",
				},
			},
		},
		filesystem = {
			filtered_items = {
				visible = false,
				hide_dotfiles = false,
				hide_gitignored = true,
			},
			follow_current_file = { enabled = true, leave_dirs_open = true },
			group_empty_dirs = true,
			use_libuv_file_watcher = true,
		},
		git_status = { window = { position = "float" } },
	},
}
